export const ActionTypes = {
  GET_NUMBER_CART: "GET_NUMBER_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  ADD_TO_CART: "ADD_TO_CART",
  ADD_TO_WISHLIST: "ADD_TO_WISHLIST",
  REMOVE_FROM_WISHLIST: "REMOVE_FROM_WISHLIST",
  INCREASE_QUANTITY:"INCREASE_QUANTITY",
  DECREASE_QUANTITY:"DECREASE_QUANTITY",
  CLEAR_CART: "CLEAR_CART", 

};
